version: '3.8'

services:
  media:
    image: mediamtx-custom
    build:
      context: mediamtx
    environment:
      - MTX_PROTOCOLS=tcp
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml
    ports:
      # RTSP
      - 8554:8554 
      - 8000:8000
      - 8001:8001 
      # RTMP
      - 1935:1935 
      # HLS
      - 8888:8888 
      # WebRTC
      - 8889:8889

