{
 "title": "Redes",
 "time": { "from": "now-2m", "to": "now" },
 "panels": [
  {
   "title": "RTSP Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(rtsp_sessions_bytes_sent[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RTSP Bytes Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(rtsp_sessions_bytes_sent[$__interval]))",
     "legendFormat": "Total transfer"
    }
   ]
  },
  {
   "title": "RTSP Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(rtsp_sessions_bytes_received[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RTSP Bytes Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(rtsp_sessions_bytes_received[$__interval]))",
     "legendFormat": "Total transfer"
    }
   ]
  },
  {
   "title": "RTSP Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum by(state) (rtsp_sessions)", "legendFormat": "__auto" }
   ]
  }
 ]
}